<a href="https://colab.research.google.com/github/cris-u/EXAMEN_SEGUNDO_PARCIAL/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## CRISTALDO ULURI TUMIRI

1. PROBAR LOS EJEMPLOS DEL PDF 911NUMPY_ALGEBRA_LINEAL

In [93]:
import numpy as np

array de una dimension

In [2]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [3]:
 # Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [4]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


FUNCION DE GENERACION

In [6]:
np.linspace(0, 10, 5)
# inicial, final, numero de elementos

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.logspace(0, 10, 5, base=np.e) # notación exponencial

array([1.00000000e+00, 1.21824940e+01, 1.48413159e+02, 1.80804241e+03,
       2.20264658e+04])

In [8]:
np.random.rand(2,3) # Matriz de números aleatorios

array([[0.76415058, 0.5086297 , 0.21747647],
       [0.81651058, 0.44955032, 0.10286477]])

In [9]:
d = np.arange(5)  # similar a range(), inicial=0, final=5-1=4
print(d)

[0 1 2 3 4]


In [10]:
np.arange(3, 7, 0.5)  # inicial, final-1 e incremento

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [11]:
d[1] = 9.7
print(d)  # array mantiene su tipo, al cambiar elementos

[0 9 2 3 4]


In [16]:
print(d*0.4)  # operaciones crean un nuevo array y tipo

[0.  3.6 0.8 1.2 1.6]


In [17]:
import numpy as np

d = np.arange(5, dtype=float)
print(d)

[0. 1. 2. 3. 4.]


In [18]:
np.diag([1,2,3]) # Matriz diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
b = np.zeros(5)  # Vector de ceros
print(b)

[0. 0. 0. 0. 0.]


In [20]:
c = np.ones((3,3)) # Matriz de unos
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
print(np.identity(2)) # Matriz identidad

[[1. 0.]
 [0. 1.]]


ATRIBUTOS

In [23]:
a = np.array([4, 8, 11, 14, 18])
print(a)

[ 4  8 11 14 18]


In [24]:
type(a) # tipo de dato

numpy.ndarray

In [25]:
a.shape # forma

(5,)

In [26]:
l = [[1, 2, 3], [3, 6, 9]]  # crea una lista
a = np.array(l)  # convierte la lista en array
print(a)

[[1 2 3]
 [3 6 9]]


In [27]:
a.shape


(2, 3)

In [28]:
print(a.dtype)  # muestra tipo de un array

int64


In [29]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Acceso a los elementos de un array

In [30]:
print(a)

[[1 2 3]
 [3 6 9]]


In [31]:
print(a[0])  # igual que en una lista de listas, la fila 0

[1 2 3]


In [32]:
print(a[1, 2])  # una coma separa los índices

9


In [33]:
print(a[1, 1:3])  # una parte de la matriz

[6 9]


In [34]:
print(a[:,1]) # la columna 1

[2 6]


In [35]:
a[1, 2] = 7 # modifica un elemento
print(a)

[[1 2 3]
 [3 6 7]]


In [36]:
a[:, 0] = [0, 9]  # modifica la columna 0
print(a)

[[0 2 3]
 [9 6 7]]


Arrays y posición de memoria

In [37]:
x = np.array([1,2,3,4])
y = x #asignación
x is y # comparación de igualdad

True

In [38]:
id(x), id(y)

(140005281356976, 140005281356976)

In [43]:
x[0] = 9
print(y)
# array([9, 2, 3, 4])

z = x[:]  # asignación
print(x is z)  # comparación de igualdad

[9 2 3 4]
False


In [44]:
id(x), id(z)

(140005281356976, 140005281357552)

In [45]:
x[0] = 8
z

array([8, 2, 3, 4])

Arrays y posición de memoria

In [48]:
x = np.array([1,2,3,4])
y = x.copy() #asignación
x is y # comparación de igualdad

False

In [49]:
id(x), id(y)

(140005281359664, 140005281360048)

In [50]:
x[0] = 9
x

array([9, 2, 3, 4])

In [51]:
y

array([1, 2, 3, 4])

Operaciones a nivel elemento

In [52]:
import numpy as np

a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

print(a + b)
print(a - b)
print(a * b)
print(b / a)
print(a % b)
print(b ** a)

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[1. 0. 3.]
[  5.   4. 216.]


In [53]:
import numpy as np

# Definir correctamente
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

# Mostrar
print("a =\n", a)
print("b =", b)

# Operación
print("a + b =\n", a + b)

a =
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
b = [-1.  3.]
a + b =
 [[0. 5.]
 [2. 7.]
 [4. 9.]]


In [54]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

print("a * a =\n", a * a)
print("b * b =", b * b)
print("a * b =\n", a * b)

a * a =
 [[ 1.  4.]
 [ 9. 16.]
 [25. 36.]]
b * b = [1. 9.]
a * b =
 [[-1.  6.]
 [-3. 12.]
 [-5. 18.]]


In [55]:
import numpy as np

a = np.arange(4.0)
print(a)

b = a * 23.4
print(b)

c = b / (a + 1)
c += 10
print(c)

arr = np.arange(100, 200)
seleccion = [5, 25, 50, 75, -5]

print(arr[seleccion])

[0. 1. 2. 3.]
[ 0.  23.4 46.8 70.2]
[10.   21.7  25.6  27.55]
[105 125 150 175 195]


In [56]:
import numpy as np

arr = np.arange(10, 20)
print(arr)

div_por_3 = arr % 3 == 0  # comparación produce un arreglo con dato boolean
print(div_por_3)

print(arr[div_por_3])  # puede usarse una lista boolean como indices (considera los True)

# Cambiando las dimensiones con reshape
arr = np.arange(10, 20).reshape((2,5))
print(arr)

[10 11 12 13 14 15 16 17 18 19]
[False False  True False False  True False False  True False]
[12 15 18]
[[10 11 12 13 14]
 [15 16 17 18 19]]


Mtodos array

In [57]:
import numpy as np

arr = np.arange(10, 20)

div_por_3 = arr % 3 == 0

print(arr.sum())  # sumatoria
print(arr.mean())  # promedio
print(arr.std())  # desviación estándar
print(arr.max())  # mayor
print(arr.min())  # menor

print(div_por_3.all())  # todos son True
print(div_por_3.any())  # alguno es True
print(div_por_3.sum())  # sumatoria (No.) de True
print(div_por_3.nonzero())  # posiciones de True

145
14.5
2.8722813232690143
19
10
False
True
3
(array([2, 5, 8]),)


Métodos array - ordenar

In [58]:
import numpy as np

a = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

a.sort()    # ordena el array físicamente, lo modifica
print(a)

x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

print(np.sort(x))   # ordena sin modificar el array x
print(x)

s = x.argsort()   # indice de elementos por orden
print(s)

print(x[s])   # muestra x ordenado, según s

[1.2 1.8 2.3 4.5 5.5 6.7]
[1.2 1.8 2.3 4.5 5.5 6.7]
[4.5 2.3 6.7 1.2 1.8 5.5]
[3 4 1 0 5 2]
[1.2 1.8 2.3 4.5 5.5 6.7]


Funciones array Numpy

In [62]:
import numpy as np

arr = np.arange(10)  # para que dé 45

print(arr.sum())
print(np.sum(arr))

45
45


Producto escalar de dos vectores

In [63]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 0, 1])

print(a @ b)
print(a.dot(b))

4
4


Módulo de un vector

In [64]:
a = np.array([3, 4])
print(np.linalg.norm(a))

5.0


Producto de dos matrices

In [65]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)

[[14 14]
 [32 32]]


In [66]:
print(a.dot(b))

[[14 14]
 [32 32]]


Matriz traspuesta

In [67]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


Traza de una matriz

In [68]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())

15


Determinante de una matriz

In [69]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

-2.0000000000000004


Matriz inversa

In [70]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))


[[-2.   1. ]
 [ 1.5 -0.5]]


Autovalores de una matriz

In [71]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))

[ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]


In [72]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eig(a))

EigResult(eigenvalues=array([ 3.00000000e+00,  1.00000000e+00, -3.36770206e-17]), eigenvectors=array([[-4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
       [-8.16496581e-01,  2.61239546e-16, -5.77350269e-01],
       [-4.08248290e-01, -7.07106781e-01,  5.77350269e-01]]))


Solución de un sistema de ecuaciones

In [73]:
import numpy as np
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))

[-1.  1.]


2. Con Numpy, dados dos vectores de enteros a y b, calcular y
mostrar (verificando que se cumplan las condiciones):
r = 8*a-2*b
producto escalar de a y b

In [74]:
import numpy as np

In [75]:
a = np.array([1, 2, 3], dtype=int)
b = np.array([4, 5, 6], dtype=int)

print(a)
print(b)

[1 2 3]
[4 5 6]


In [92]:
print(a.shape)
print(b.shape)

if a.shape == b.shape:
    print("✔ Vectores válidos")
else:
    print("X Error: dimensiones diferentes")

(3,)
(3,)
✔ Vectores válidos


In [77]:
r = 8*a - 2*b
print(r)

[ 0  6 12]


In [78]:
producto = a @ b
print(producto)

32


3. CON NUMPY, DADAS DOS MATRICES m1 Y m2, CALCULAR Y MOSTRAR (VERIFICANDO QUE SE CUMPLAN LAS CONDICIONES):

 s = m1+m2

 p = m1*m2

 inversa de m1

 determinante de m2

In [80]:
import numpy as np

In [81]:
m1 = np.array([[1, 2], [3, 4]], dtype=float)
m2 = np.array([[5, 6], [7, 8]], dtype=float)

print("m1 =\n", m1)
print("m2 =\n", m2)

m1 =
 [[1. 2.]
 [3. 4.]]
m2 =
 [[5. 6.]
 [7. 8.]]


In [91]:
# Para suma y producto elemento a elemento
if m1.shape == m2.shape:
    print("✔ Matrices con misma dimensión")
else:
    print("X Error: dimensiones diferentes")

# Para inversa y determinante
if m1.shape[0] == m1.shape[1]:
    print("✔ m1 es cuadrada")
else:
    print("X m1 no es cuadrada")

if m2.shape[0] == m2.shape[1]:
    print("✔ m2 es cuadrada")
else:
    print("X m2 no es cuadrada")

✔ Matrices con misma dimensión
✔ m1 es cuadrada
✔ m2 es cuadrada


In [84]:
s = m1 + m2
print("Suma:\n", s)

Suma:
 [[ 6.  8.]
 [10. 12.]]


In [85]:
p = m1 * m2
print("Producto elemento a elemento:\n", p)

Producto elemento a elemento:
 [[ 5. 12.]
 [21. 32.]]


In [89]:
det_m1 = np.linalg.det(m1)

if det_m1 != 0:
    inv_m1 = np.linalg.inv(m1)
    print("Inversa de m1:\n", inv_m1)
else:
    print("X m1 no tiene inversa")

Inversa de m1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [87]:
det_m2 = np.linalg.det(m2)
print("Determinante de m2:", det_m2)

Determinante de m2: -2.000000000000005
